import { MailerService } from '@nestjs-modules/mailer';
export declare class MailService {
    private mailerService;
    constructor(mailerService: MailerService);
    private fmt;
    sendOrderConfirmation(params: {
        to: string;
        name: string;
        orderId: string;
        productName: string;
        quantity: number;
        total: number;
        invoiceCode: string;
    }): Promise<void>;
    sendDesignerAssigned(params: {
        to: string;
        customerName: string;
        designerName: string;
        productName: string;
        orderId: string;
        zoomLink?: string;
    }): Promise<void>;
    sendDesignApproved(params: {
        to: string;
        customerName: string;
        productName: string;
        orderId: string;
        fileUrl?: string;
    }): Promise<void>;
    sendDeliveryStarted(params: {
        to: string;
        customerName: string;
        productName: string;
        courierName: string;
        courierPhone: string;
        address: string;
    }): Promise<void>;
    sendDeliveryCompleted(params: {
        to: string;
        customerName: string;
        productName: string;
    }): Promise<void>;
    sendQuoteToCustomer(q: {
        to: string;
        name: string;
        phone: string;
        quote_number: string;
        product_name: string;
        quantity: number;
        pages: number;
        size: string;
        width_mm: number;
        height_mm: number;
        paper_type: string;
        paper_gsm: number;
        color_mode: string;
        sides: string;
        finishing: string;
        binding: string;
        unit_price: number;
        total_price: number;
        valid_until: Date;
        breakdown: any;
    }): Promise<void>;
    sendDailyReport(adminEmail: string, quotes: any[], date: string): Promise<void>;
}
