-- Seed 20 layouts for business card product
DO $$
DECLARE pid uuid := '57229fb9-12d5-4104-863f-d95e619f30d8';
BEGIN

INSERT INTO bc_layouts (id, product_id, name, name_mn, type, front_json, back_json, sort_order, is_active) VALUES
(gen_random_uuid(), pid, 'Классик цагаан', 'Классик цагаан', 'minimal', '[{"type":"name","position":"top-left","size":"lg"},{"type":"title","position":"top-left","size":"sm"},{"type":"phone","position":"bottom-left","size":"sm"},{"type":"email","position":"bottom-left","size":"sm"},{"type":"qr","position":"right-center","size":"md"}]', '[{"type":"logo","position":"center","size":"lg"},{"type":"company","position":"center","size":"md"}]', 0, true),
(gen_random_uuid(), pid, 'Харанхуй элегант', 'Харанхуй элегант', 'business', '[{"type":"name","position":"top-left","size":"lg","bg":"#111","text":"#fff"},{"type":"phone","position":"bottom-left","size":"sm"},{"type":"qr","position":"right-center","size":"md"}]', '[{"type":"logo","position":"center","size":"lg","bg":"#111","text":"#fff"}]', 1, true),
(gen_random_uuid(), pid, 'BizPrint брэнд', 'BizPrint брэнд', 'creative', '[{"type":"name","position":"top-center","size":"lg","bg":"#FF6B00","text":"#fff"},{"type":"phone","position":"bottom","size":"sm"}]', '[{"type":"logo","position":"center","size":"lg","bg":"#FF6B00","text":"#fff"}]', 2, true),
(gen_random_uuid(), pid, 'Албан ёсны хөх', 'Албан ёсны хөх', 'business', '[{"type":"company","position":"top-left","size":"sm","accent":"#3B82F6"},{"type":"name","position":"top-left","size":"lg"},{"type":"phone","position":"bottom-left","size":"sm"}]', '[{"type":"logo","position":"center","size":"lg","bg":"#1A1A2E","text":"#fff"}]', 3, true),
(gen_random_uuid(), pid, 'Минимал цэвэр', 'Минимал цэвэр', 'minimal', '[{"type":"name","position":"top-left","size":"lg"},{"type":"title","position":"top-left","size":"sm"},{"type":"phone","position":"bottom-left","size":"sm"}]', '[{"type":"company","position":"center","size":"lg"}]', 4, true),
(gen_random_uuid(), pid, 'Градиент ягаан', 'Градиент ягаан', 'creative', '[{"type":"name","position":"top-left","size":"lg","bg":"#6D28D9","text":"#fff"},{"type":"phone","position":"bottom-left","size":"sm"},{"type":"qr","position":"right-center","size":"md"}]', '[{"type":"logo","position":"center","size":"lg","bg":"#6D28D9","text":"#fff"}]', 5, true),
(gen_random_uuid(), pid, 'Ногоон байгаль', 'Ногоон байгаль', 'creative', '[{"type":"name","position":"top-left","size":"lg","accent":"#059669"},{"type":"phone","position":"bottom-left","size":"sm"}]', '[{"type":"logo","position":"center","size":"lg","bg":"#059669","text":"#fff"}]', 6, true),
(gen_random_uuid(), pid, 'Улаан идэвхтэй', 'Улаан идэвхтэй', 'full', '[{"type":"name","position":"top-left","size":"lg","accent":"#DC2626"},{"type":"phone","position":"bottom-left","size":"sm"},{"type":"qr","position":"right-center","size":"md"}]', '[{"type":"logo","position":"center","size":"lg","bg":"#DC2626","text":"#fff"}]', 7, true),
(gen_random_uuid(), pid, 'Алтан дээд зэрэг', 'Алтан дээд зэрэг', 'business', '[{"type":"name","position":"top-left","size":"lg","accent":"#D4AF37"},{"type":"phone","position":"bottom-left","size":"sm"}]', '[{"type":"logo","position":"center","size":"lg","bg":"#1A1A1A","text":"#D4AF37"}]', 8, true),
(gen_random_uuid(), pid, 'Хөнгөн саарал', 'Хөнгөн саарал', 'minimal', '[{"type":"name","position":"top-left","size":"lg"},{"type":"phone","position":"bottom-left","size":"sm"}]', '[{"type":"company","position":"center","size":"lg","bg":"#F3F4F6","text":"#333"}]', 9, true),
(gen_random_uuid(), pid, 'Хос зурвас', 'Хос зурвас', 'full', '[{"type":"company","position":"top-left","size":"sm"},{"type":"name","position":"top-left","size":"lg"},{"type":"phone","position":"bottom-left","size":"sm"},{"type":"qr","position":"right-center","size":"md"}]', '[{"type":"logo","position":"center","size":"lg"},{"type":"social","position":"bottom","size":"sm"}]', 10, true),
(gen_random_uuid(), pid, 'Японы минимал', 'Японы минимал', 'minimal', '[{"type":"name","position":"top-center","size":"lg"},{"type":"phone","position":"bottom","size":"sm"}]', '[{"type":"company","position":"center","size":"md"}]', 11, true),
(gen_random_uuid(), pid, 'Технологи хөх', 'Технологи хөх', 'business', '[{"type":"name","position":"top-left","size":"lg","accent":"#2563EB"},{"type":"phone","position":"bottom-left","size":"sm"},{"type":"qr","position":"right-center","size":"md"}]', '[{"type":"logo","position":"center","size":"lg","bg":"#1E3A5F","text":"#fff"}]', 12, true),
(gen_random_uuid(), pid, 'Загварлаг ягаан', 'Загварлаг ягаан', 'creative', '[{"type":"name","position":"top-center","size":"lg","accent":"#EC4899"},{"type":"phone","position":"bottom","size":"sm"}]', '[{"type":"logo","position":"center","size":"lg","bg":"#EC4899","text":"#fff"}]', 13, true),
(gen_random_uuid(), pid, 'Корпорэйт саарал', 'Корпорэйт саарал', 'business', '[{"type":"company","position":"top-left","size":"sm"},{"type":"name","position":"top-left","size":"lg"},{"type":"phone","position":"bottom-left","size":"sm"}]', '[{"type":"logo","position":"center","size":"lg","bg":"#374151","text":"#fff"}]', 14, true),
(gen_random_uuid(), pid, 'Хар алтан', 'Хар алтан', 'full', '[{"type":"name","position":"top-left","size":"lg","bg":"#0A0A0A","text":"#D4AF37"},{"type":"phone","position":"bottom-left","size":"sm"},{"type":"qr","position":"right-center","size":"md"}]', '[{"type":"logo","position":"center","size":"lg","bg":"#0A0A0A","text":"#D4AF37"}]', 15, true),
(gen_random_uuid(), pid, 'Цэнхэр далай', 'Цэнхэр далай', 'creative', '[{"type":"name","position":"top-left","size":"lg","accent":"#0891B2"},{"type":"phone","position":"bottom-left","size":"sm"}]', '[{"type":"logo","position":"center","size":"lg","bg":"#0891B2","text":"#fff"}]', 16, true),
(gen_random_uuid(), pid, 'Энгийн цагаан', 'Энгийн цагаан', 'minimal', '[{"type":"name","position":"top-left","size":"lg"},{"type":"phone","position":"bottom-left","size":"sm"}]', '[{"type":"company","position":"center","size":"lg"}]', 17, true),
(gen_random_uuid(), pid, 'Бүрэн мэдээлэл', 'Бүрэн мэдээлэл', 'full', '[{"type":"company","position":"top-left","size":"sm"},{"type":"name","position":"top-left","size":"lg"},{"type":"phone","position":"bottom-left","size":"sm"},{"type":"email","position":"bottom-left","size":"sm"},{"type":"qr","position":"right-center","size":"md"}]', '[{"type":"logo","position":"center","size":"lg"},{"type":"social","position":"bottom","size":"sm"}]', 18, true),
(gen_random_uuid(), pid, 'Премиум хар', 'Премиум хар', 'business', '[{"type":"name","position":"top-left","size":"lg","bg":"#111","text":"#fff","accent":"#FF6B00"},{"type":"phone","position":"bottom-left","size":"sm"},{"type":"qr","position":"right-center","size":"md"}]', '[{"type":"logo","position":"center","size":"lg","bg":"#111","text":"#FF6B00"}]', 19, true);

END $$;
